In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import sqlite3
import numpy as np

import database (sql)

In [2]:
conn=sqlite3.connect('customer_churn.db')
sql_query="""
select name from sqlite_master where type='table'
"""

In [3]:
tables=pd.read_sql(""" select name from sqlite_master where type='table' """,conn)
tables

              name
0      db_customer
1  db_subscription
2       db_support

create dataframe

In [4]:
for table_name in tables['name']:
    df=pd.read_sql(f"select * from {table_name}",conn)
    globals()[f'df_{table_name}']=df
    print(f'created dataframe: df_{table_name}')
conn.close()

created dataframe: df_db_customer
created dataframe: df_db_subscription
created dataframe: df_db_support

removing the unnessary columns

In [5]:
df_db_customer.drop(columns=['interests','pincode'],inplace=True)

changin data type of dob column

In [6]:
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

data standardization -gender

In [7]:
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

updating missing values

In [8]:
df_db_customer[df_db_customer['country'].isna()]

    customerid    name country      state  gender        dob
5   0013-MHZWF   durga     NaN      Delhi  Female 1988-12-10
8   0015-UOCOJ    maya     NaN  Kathmandu  Female 1985-07-07
12  0018-NYROU  chitra     NaN  Telangana  Female 2004-12-01

In [9]:
state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()
df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

now miving on next table

In [10]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

now changin the data type of dates columns

In [15]:
date_col=['subscription_start_date','cancellation_date','renewal_date']
df_db_subscription[date_col]=df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     datetime64[us]
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     datetime64[us]
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      datetime64[us]
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[us](3), float64(1), int64(2), str(5)
memory usage: 1.9 KB

now the last table

In [21]:
df_db_support.head()

   customerid       complaint_date escalations  csat_score
0  0003-MKNFE  2024-08-28 00:00:00           N          60
1  0003-MKNFE  2024-08-28 00:00:00           Y          10
2  0013-EXCHZ  2024-01-20 00:00:00           Y          20
3  0013-MHZWF  2025-03-18 00:00:00           N          90
4  0013-SMEOE  2024-11-01 00:00:00           N          30

In [ ]:
df_db_support.drop(columns=['col_1','comment'],inplace=True)

   customerid       complaint_date escalations  csat_score
0  0003-MKNFE  2024-08-28 00:00:00           N          60
1  0003-MKNFE  2024-08-28 00:00:00           Y          10
2  0013-EXCHZ  2024-01-20 00:00:00           Y          20
3  0013-MHZWF  2025-03-18 00:00:00           N          90
4  0013-SMEOE  2024-11-01 00:00:00           N          30
5  0017-IUDMW  2024-04-10 00:00:00           Y          25
6  0019-EFAEP  2024-09-27 00:00:00           Y          30
7  0022-TCJCI  2024-09-13 00:00:00           Y          10
8  0022-TCJCI  2024-09-14 00:00:00           N          90

changing data type of date

In [22]:
df_db_support['complaint_date']=pd.to_datetime(df_db_support['complaint_date'])

In [23]:
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      datetime64[us]
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 420.0 bytes

.................................... Feature engineering and data analysis ...........................................

adding a flag to churn users

creating a new col using existing col

In [25]:
df_db_subscription['churn_flag']=np.where(df_db_subscription['cancellation_date'].notna(),1,0)

In [43]:
df_db_customer.shape

(21, 6)

removing duplicates from df_db_support

In [37]:
df_db_support['complaint_count']=df_db_support.groupby('customerid')['customerid'].transform('count')

In [40]:
df_db_support=df_db_support.sort_values('complaint_date').drop_duplicates('customerid',keep='last')

now merging the data

In [41]:
df=(df_db_subscription
    .merge(df_db_customer,on="customerid",how='left')
    .merge(df_db_support,on='customerid',how='left'))

In [45]:
df.shape

(21, 21)